spring.application.name=connectionsService

server.port = 9030
server.servlet.context-path = /api/v1/connections

spring.neo4j.uri=neo4j+s://cea21eed.databases.neo4j.io
spring.neo4j.authentication.username=cea21eed
spring.neo4j.authentication.password=C-w7vWkT5HePw4DXxjMDX6gPRe2pgMzIFGRk302gRYE
spring.neo4j.database=cea21eed
