spring.application.name=userService
server.port=9010

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/orbisin_userDB
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
